services:
  backend:
    build: ./backend
    container_name: musicplayer-backend
    environment:
      - DB_PATH=/data/db.sqlite3
    volumes:
      - backend_data:/data
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: musicplayer-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  backend_data: